Fft improvements
nv-legate/cupynumeric pull request #732
Opened 2022-12-08 21:42 UTC by mfoerste4

This PR is a re-factorization of the cufft wrapper task in order to

* remove the 3D-FFT limit
* allow for data parallel execution if feasible
* extend cuftPlanCache for advanced layouts

NOTE: This is a new PR based on #700 which had trouble with the CI due to the branch name.

2023-01-06 17:22 UTC, mfoerste4 commented
@magnatelee, ready for another review round - the cufft plan cache (#729 ) improves the startup time of asynchronous cufft tasks significantly.

2023-03-29 03:44 UTC, magnatelee requested changes

2023-03-29 03:44 UTC, magnatelee commented on cunumeric/deferred.py
> +            if input.ndim > len(set(axes)):
I think the `axes` should be sanitized before we get to this function.

2023-03-29 03:44 UTC, magnatelee commented on cunumeric/fft/fft.py
> +    Multiple GPUs
Same comment here. Let's make some notes on when we can parallelize FFTs.

2023-03-29 03:44 UTC, magnatelee commented on src/cunumeric/cuda_help.h
> +struct cufftPlanParms {
a nitpick: "parms" seems a bit unusual abbreviation for "parameters". ("params" would be a typical name)

2023-06-30 14:39 UTC, merged